image:
  file: .gitpod.Dockerfile
tasks:
  - command: |
      gp await-port 80 && gp preview $(gp url 80)/web/viewer.html && echo '[{"name": "Firefox","path": "/usr/bin/firefox"}]' | jq '.' > test/resources/browser_manifests/browser_manifest.json

  - init: npm install -g gulp-cli && npm install
    command: gulp server
ports:
  - port: 80
    onOpen: ignore
  - port: 6080
    onOpen: ignore
